# - The name of the project is FerrumFIX.
# - The repository is `ferrum-fix`.
# - The crates are named `fefix`, `fefix_derive`, etc..

[workspace]
members = [
    "fefix",
    "fefix_derive",
    "examples/codegen_fix42",
    "examples/codegen_webserver",
    "examples/web_json_to_tagvalue",
    "examples/tcp_sofh",
    "examples/tls_fixua_acceptor",
]