[package]
name = "fasters"
version = "0.1.0"
edition = "2018"
authors = ["Filippo Costa @neysofu"]
homepage = "https://github.com/neysofu/fasters"
repository = "https://github.com/neysofu/fasters"
publish = true
readme = "README.md"
keywords = ["fix", "fast", "protocol", "finance", "streaming"]
categories = ["network-programming", "parser-implementations", "encoding"]
license = "MIT"

[features]
default = ["fixml", "compact"]
fixml = ["quick-xml"]
compact = ["nom"]

[dependencies]
bitvec = "0.14"
failure = "0.1.5"
codegen = "0.1.1"
quick-xml = { version = "0.17.2", optional = true }
nom = { version = "5", optional = true }

[dev-dependencies]
quickcheck = "0.8"
quickcheck_macros = "0.8"
