# - The name of the project is FerrumFIX.
# - The repository is `ferrum-fix`.
# - The crates are named `fefix`, `fefix_derive`, etc..

[profile.release]
lto = true

[workspace]
members = [
    # Public crates.
    "fefix",
    "fefix_derive",
    # Private crates.
    "examples/codegen_fix42",
    "examples/codegen_webserver",
    "examples/web_json_to_tagvalue",
    "examples/tcp_sofh",
    "examples/tls_fixua_acceptor",
    "tests/codegen_fix44",
]
