[package]
name = "fasters"
version = "0.1.0"
edition = "2018"
authors = ["Filippo Costa @neysofu"]
homepage = "https://github.com/neysofu/fasters"
repository = "https://github.com/neysofu/fasters"
description = "FIX & FAST (FIX Adapted for STreaming) in pure Rust."
publish = true
readme = "README.md"
keywords = ["fix", "fast", "protocol", "finance", "streaming"]
categories = ["network-programming", "parser-implementations", "encoding"]
license = "MIT"

[dependencies]
bitvec = "0.14"
failure = "0.1.5"
codegen = "0.1.1"
serde = { version = "1.0", features = [ "derive" ] }
quick-xml = { version = "0.17.2", features = [ "serialize" ] }
nom = "5"
rust-embed = "5.2.0"

[dev-dependencies]
quickcheck = "0.8"
quickcheck_macros = "0.8"
