# - The name of the project is FerrumFIX.
# - The repository is `ferrum-fix`.
# - The crates are named `fefix`, `fefix_derive`, etc..

[profile.release]
lto = true

[workspace]
members = [
    "fefix",
    "fefix_derive",
    "examples/00_decode_fix",
    "examples/03_decode_fix_stream",
    "examples/05_coinbase_codegen",
    "examples/10_encode_new_order_single",
    "examples/20_fix_initiator",
    "examples/web_json_to_tagvalue",
    "examples/30_tcp_sofh",
    "examples/tls_fixua_acceptor",
    "tests/codegen_fix44",
]
