[package]
name = "fefix"
version = "0.4.0"
edition = "2018"
authors = ["Filippo Costa @neysofu"]
homepage = "https://github.com/neysofu/ferrum-fix"
repository = "https://github.com/neysofu/ferrum-fix"
description = "FIX & FAST (FIX Adapted for STreaming) in pure Rust."
publish = true
readme = "../README.md"
keywords = ["fix", "fast", "protocol", "finance", "streaming"]
categories = ["network-programming", "parser-implementations", "encoding"]
license = "MIT"

[lib]
name = "fefix"

[features]
default = ["repo_v2010", "repo_v50sp2ep254", "expose_openssl", "expose_tokio"]
repo_v50sp2ep254 = []
repo_v2010 = []
expose_openssl = []
expose_tokio = []

[dependencies]
bitvec = "0.18.3"
boolinator = "2.4.0"
chrono = "0.4"
futures = "0.3.8"
futures-lite = "1"
Inflector = "0.11.4"
openssl = "0.10.32"
phf = { version = "0.8", features = ["macros"] }
roxmltree = "0.13.0"
rust-embed = "5.7"
serde = "1"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
uuid = { version = "0.8.1", features = ["v4"] }
fefix_derive = { path = "../fefix_derive" }

[dev-dependencies]
arbitrary = { version = "0.4", features = ["derive"] }
quickcheck = "0.8"
quickcheck_derive = "0.3"
quickcheck_macros = "0.8"
syn = { version = "1", features = ["full"] }