[package]
name = "example_fix_initiator"
version = "0.1.0"
edition = "2018"

[dependencies]
fefix = { path = "../../fefix" }
tokio = { version = "1", features = ["net", "io-util"] }
tokio-util = { version = "0.6", features = ["compat"] }